name: Copado CRT Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main

jobs:
  run-crt-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: verify java version
        run: java -version

      - name: install copado crt dependencies
        run: |
           pip install robotframework
           pp install robotframework-qweb
           pip install copado-robotic-testing

      - name: run copado tests
        run: |
          rpbot tests/crt_validation.robot
           
      - name: upload CRT testresults
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crt-results
          path: results/
        
       
        


