name: copado CRT pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-crt-tests:
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim

    steps:
      - uses: actions/checkout@v4

      - name: install robot framework
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
      - name: run crt tests
        run: |
          robot tests/crt_validation.robot
           
      - name: upload CRT testresults
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crt-results
          path: results/
        
       
        


