name: copado CRT pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-crt-tests:
    runs-on: ubuntu-latest

    container:
      image: copado/robotic-testing:latest

    steps:
      - uses: actions/checkout@v4

      - name: run copado crt latest
        run: |
          robot tests/crt_validation.robot
           
      - name: upload CRT testresults
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crt-results
          path: |
            output.xml
            log.html
            report.html
        
       
        


