name: Copado CRT Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main

jobs:
  run-crt-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: verify java version
        run: java -version

      - name: Run Copado CRT tests
        run: |
           pip install robotframework
           robot --outputdir results tests

       - name: upload CRT test results
        if: always()
        uses: actions/upload-aertifact@v4
        with:
          name: crt-results
          path: results/
      

       

        


